# Site settings
title: 琉球大学公式ホームページ
univ_name: 国立大学法人 琉球大学
tel: 098-895-8012
email: kohokoho@jim.u-ryukyu.ac.jp
address: 沖縄県中頭郡西原町字千原1番地
postal_code: 903-0213
copyright: Copyright(C)1997-2015,UNIVERSITY OF THE RYUKYUS
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.u-ryukyu.ac.jp" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
